version: '3.7'
services:
  frontend_app:
      build:
        context: ./
        dockerfile: Dockerfile
      container_name: mpp_cimahi_offline
      volumes:
        - './:/app'
        - '/app/node_modules'
      ports:
        - 3000:3000
      stdin_open: true
      command: npm start
      env_file:
        - ./.env